runtime: python311

instance_class: F2

env_variables:
  GEMINI_API_KEY: ${GEMINI_API_KEY}
  CLAUDE_API_KEY: ${CLAUDE_API_KEY}
  CLAUDE_MODEL: claude-3-sonnet-20240229

handlers:
  - url: /static
    static_dir: public
    
  - url: /.*
    script: auto

entrypoint: gunicorn -b :$PORT app:app 